#!/usr/bin/env bash

# For debugging

set -xv
set -eu

# Load common functions
source "$(dirname "${BASH_SOURCE[0]}")/common.bsh"

set_disk_variables "${1}"

for point in "/dev/mapper/${name}" "/dev/mapper/${name}"_*; do
  if [ -e "${point}" ]; then
    set_disk_variables_unencrypted "${point}" "${serial}"

    umount "/media/${name}" || :
    cryptsetup luksClose "${point}" || :
  fi
done

sed -i "/^${uid}!!/d" "${STORAGE_CONF}"

if [ -n "${mount_location+set}" ] && [ -d "/${mount_location}" ]; then
  rmdir "/${mount_location}"
fi

sqlite3 -init /opt/usb-auto-decrypt/init.sql /var/readynasd/db.sq3 "
  DELETE FROM 'share' WHERE name='${name-}';"

sqlite3 -init /opt/usb-auto-decrypt/init.sql /var/readynasd/db.sq3 "
  DELETE FROM 'usb_storage' WHERE name='${name-}';"

sqlite3 -init /opt/usb-auto-decrypt/init.sql -readonly /var/readynasd/db.sq3 "
  SELECT * FROM 'usb_storage' WHERE name='${name-}';
  SELECT * FROM 'share' WHERE name='${name-}'"

ls /dev/mapper /media
