#!/usr/bin/env bash

CWD="$(dirname "${BASH_SOURCE[0]}")"

# Install udev rule
cp "${CWD}"/*.rules /etc/udev/rules.d/
udevadm control --reload

# Install scripts
mkdir -p /opt/usb-auto-decrypt
cp "${CWD}/decrypt_usb" "${CWD}/init.sql" "${CWD}/common.bsh" /opt/usb-auto-decrypt/
chmod 755 /opt/usb-auto-decrypt /opt/usb-auto-decrypt/decrypt_usb
chmod 644 /opt/usb-auto-decrypt/init.sql /opt/usb-auto-decrypt/common.bsh

# install services
cp "${CWD}"/*.service /etc/systemd/system/
systemctl daemon-reload