#!/usr/bin/env bash

# set -xv
set -eu

# Load common functions
source "$(dirname "${BASH_SOURCE[0]}")/common.bsh"

sys_path="/sys${1}"
serial="${2}"
uuid="${3}"

name="$(get_name "${serial}-${uuid}" "${sys_path}")"

# Try and close them off. If they all close, great, if not, oh well. We tried.
for point in "/dev/mapper/${name}" "/dev/mapper/${name}"_*; do
  if [ -e "${point}" ]; then
    cryptsetup luksClose "${point}" || :
  fi
done

IFS=$'\n'
echo $'ok\n'"${*}" > /tmp/bar
